version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7799:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false